import type { FollowupCase } from "../../types/followup";

export const mockFollowupCases: FollowupCase[] = [
  {
    id: "case-01",
    requestNo: "DEMO-WC-001",
    partnerOne: "林晨光",
    partnerTwo: "周語晴",
    primaryContact: "周語晴",
    phone: "0900-000-101",
    submittedAt: "2026-07-28",
    eventDate: "2027-03-20",
    tableCount: 18,
    personality: "月光詩人",
    recommendedHall: "紫艷好事",
    consultations: [
      { date: "2026-07-29", note: "偏好溫柔燈光與簡潔流程，預計先與家人確認桌數。" },
      { date: "", note: "" },
      { date: "", note: "" },
    ],
    status: "洽談中",
    closedDate: "",
  },
  {
    id: "case-02",
    requestNo: "DEMO-WC-002",
    partnerOne: "陳星河",
    partnerTwo: "黃沐恩",
    primaryContact: "陳星河",
    phone: "0900-000-202",
    submittedAt: "2026-07-25",
    eventDate: "2027-01-16",
    tableCount: 26,
    personality: "星光主角",
    recommendedHall: "愛丁堡",
    consultations: [
      { date: "2026-07-26", note: "希望進場有舞台效果，也重視賓客觀看視線。" },
      { date: "2026-08-02", note: "已完成場勘，雙方家長皆喜歡愛丁堡的空間感。" },
      { date: "2026-08-05", note: "確認檔期與基本方案，後續安排簽約。" },
    ],
    status: "已訂",
    closedDate: "2026-08-05",
  },
  {
    id: "case-03",
    requestNo: "DEMO-WC-003",
    partnerOne: "張予安",
    partnerTwo: "吳若棠",
    primaryContact: "張予安",
    phone: "0900-000-303",
    submittedAt: "2026-07-21",
    eventDate: "2027-05-08",
    tableCount: 12,
    personality: "森林收藏家",
    recommendedHall: "法蘿",
    consultations: [
      { date: "2026-07-23", note: "喜歡自然材質與午宴氛圍，仍在比較交通便利性。" },
      { date: "2026-07-30", note: "希望調整預算配置，已提供精簡版方案。" },
      { date: "", note: "" },
    ],
    status: "洽談中",
    closedDate: "",
  },
  {
    id: "case-04",
    requestNo: "DEMO-WC-004",
    partnerOne: "許向晚",
    partnerTwo: "鄭以辰",
    primaryContact: "許向晚",
    phone: "0900-000-404",
    submittedAt: "2026-07-16",
    eventDate: "2027-02-27",
    tableCount: 34,
    personality: "歡樂導演家",
    recommendedHall: "世紀盛典",
    consultations: [
      { date: "2026-07-18", note: "賓客人數較多，希望流程熱鬧、互動感強。" },
      { date: "2026-07-24", note: "因家人改變宴客地區，暫停新莊場地規劃。" },
      { date: "", note: "" },
    ],
    status: "流失",
    closedDate: "2026-07-24",
  },
  {
    id: "case-05",
    requestNo: "DEMO-WC-005",
    partnerOne: "蔡景舟",
    partnerTwo: "葉心恬",
    primaryContact: "葉心恬",
    phone: "0900-000-505",
    submittedAt: "2026-07-12",
    eventDate: "2026-12-19",
    tableCount: 10,
    personality: "溫柔聚會家",
    recommendedHall: "伊麗莎白",
    consultations: [
      { date: "2026-07-13", note: "希望小而溫馨，重視餐點與長輩的舒適度。" },
      { date: "2026-07-19", note: "已確認方案，等待家長決定宴客日期。" },
      { date: "2026-07-22", note: "因婚期延期，雙方決定取消原檔期。" },
    ],
    status: "退訂",
    closedDate: "2026-07-22",
  },
  {
    id: "case-06",
    requestNo: "DEMO-WC-006",
    partnerOne: "郭明澄",
    partnerTwo: "蘇芷晴",
    primaryContact: "郭明澄",
    phone: "0900-000-606",
    submittedAt: "2026-08-01",
    eventDate: "2027-06-12",
    tableCount: 22,
    personality: "儀式築夢者",
    recommendedHall: "沐曦",
    consultations: [
      { date: "2026-08-03", note: "對證婚儀式與進場節奏很有想法，已預約下一次場勘。" },
      { date: "", note: "" },
      { date: "", note: "" },
    ],
    status: "洽談中",
    closedDate: "",
  },
];
