"use client";
import type { Dispatch, SetStateAction } from "react";
import quizJson from "../../data/wedding-quiz.json";
import hallJson from "../../data/halls.json";
import { getPersonalityById } from "../../lib/personalityData";
import type { HallsData } from "../../types/hall";
import type { RecommendationSession } from "../../types/recommendation-session";
import type { WeddingQuizData } from "../../types/wedding-quiz";
import { WEDDING_PERSONALITY_WEIGHT_KEYS } from "../../types/wedding-personality";
import { BottomActionBar, BottomActions, PrimaryButton } from "./Ui";
import { HallRecommendationCard, comfortText, hallById } from "./HallComponents";
import { PersonalityStoryContent } from "../personality/PersonalityStoryContent";

const questions = (quizJson as WeddingQuizData).questions.filter(q=>q.status==="active").sort((a,b)=>a.order-b.order);
const hallsData = hallJson as unknown as HallsData;
const labels: Record<string,string> = { romantic:"浪漫",elegant:"優雅",modern:"現代",luxurious:"奢華",warm:"溫暖",party:"派對",ceremony:"儀式",interactive:"互動",photoFriendly:"拍照氛圍",familyOriented:"家庭感" };
type Setter = Dispatch<SetStateAction<RecommendationSession>>;

export function QuizOptionIcon({ variant }: { variant: number }) {
 const paths = [
  <path key="a" d="M12 3v18M3 12h18M6 6l12 12M18 6 6 18" />,
  <path key="b" d="M12 3 21 12 12 21 3 12 12 3Zm0 5v8M8 12h8" />,
  <path key="c" d="M12 3a9 9 0 1 1 0 18 9 9 0 0 1 0-18Zm-4 9h8M12 8v8" />,
  <path key="d" d="m12 3 9 17H3L12 3Zm0 6v6M12 18h.01" />,
 ];
 return <span className="quiz-option-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">{paths[variant%paths.length]}</svg></span>;
}

export function WelcomeStep({ next, hasProgress=false, restart }: { next():void; hasProgress?:boolean; restart?():void }) { return <section className="dna-step welcome-step fade-in"><div className="welcome-glow" aria-hidden="true"/><p className="eyebrow">DENWELL · WEDDING DNA</p><h1>找到最像你們的<br/>婚禮空間</h1><p>透過五個故事章節，探索你們的婚禮個性，<br/>並從新莊典華宴會空間中找出最適合的選擇。</p><div className="welcome-actions"><PrimaryButton onClick={next}>{hasProgress?"繼續上次進度":"開始測驗"} <span>→</span></PrimaryButton>{hasProgress&&restart?<button className="button button-ghost" onClick={restart}>重新開始</button>:null}</div><small>預估完成時間約 3 分鐘 · 進度會保存在此裝置</small></section>; }

export function BasicInfoStep({ session, setSession, next, back, errors }: {session:RecommendationSession;setSession:Setter;next():void;back():void;errors:string[]}) {
 const b=session.basicInfo; const update=(key:string,value:unknown)=>setSession(s=>({...s,basicInfo:{...s.basicInfo,[key]:value}}));
 return <section className="dna-step"><p className="eyebrow">先認識你們的婚禮輪廓</p><h1>基本資料</h1><div className="form-grid section-card">
  <label className="full" htmlFor="wedding-date">婚禮日期<input id="wedding-date" type="date" value={b.weddingDate} disabled={b.dateUndecided} onChange={e=>update("weddingDate",e.target.value)}/></label><label className="check full"><input type="checkbox" checked={b.dateUndecided} onChange={e=>update("dateUndecided",e.target.checked)}/> 日期還沒決定</label>
  <label className="full">宴會時段<select value={b.timeSlot} onChange={e=>update("timeSlot",e.target.value)}><option value="undecided">尚未決定</option><option value="lunch">午宴</option><option value="dinner">晚宴</option></select></label>
  <label>預計桌數<input inputMode="numeric" type="number" min="1" value={b.estimatedTables??""} disabled={b.tableCountUndecided} onChange={e=>update("estimatedTables",e.target.value?Number(e.target.value):null)} placeholder="例如 24"/></label><label>預計人數<input inputMode="numeric" type="number" min="1" value={b.estimatedGuests??""} onChange={e=>update("estimatedGuests",e.target.value?Number(e.target.value):null)} placeholder="例如 200"/></label>
  <label className="check full"><input type="checkbox" checked={b.tableCountUndecided} onChange={e=>update("tableCountUndecided",e.target.checked)}/> 桌數尚未決定</label></div>{errors.length?<div className="inline-errors">{errors.map(x=><p key={x}>{x}</p>)}</div>:null}<BottomActions><button onClick={back}>返回</button><PrimaryButton onClick={next}>開始測驗</PrimaryButton></BottomActions></section>;
}

export function QuizStep({session,setSession,index,setIndex,next,back}: {session:RecommendationSession;setSession:Setter;index:number;setIndex(n:number):void;next():void;back():void}) {
 const q=questions[index]; const answer=session.answers.find(a=>a.questionId===q.id); const select=(optionId:string)=>setSession(s=>({...s,answers:[...s.answers.filter(a=>a.questionId!==q.id),{questionId:q.id,optionId}]}));
 const previous=()=>index===0?back():setIndex(index-1); const forward=()=>index===questions.length-1?next():setIndex(index+1);
 return <section className="dna-step quiz-step slide-up"><div className="question-count"><b>{index+1}</b> / {questions.length}</div><div className="quiz-progress"><div><i style={{width:`${((index+1)/questions.length)*100}%`}}/></div></div><article className="scenario-card"><h1>{q.title}</h1></article><div className="option-list" role="radiogroup" aria-label={q.title}>{q.options.map((o,i)=><button type="button" role="radio" aria-checked={answer?.optionId===o.optionId} key={o.optionId} className={answer?.optionId===o.optionId?"selected":""} onClick={()=>select(o.optionId)}><QuizOptionIcon variant={i}/><span><strong>{o.text}</strong></span></button>)}</div><BottomActionBar><div className="quiz-navigation"><button type="button" className="button button-secondary" onClick={previous}>返回</button><PrimaryButton disabled={!answer} onClick={forward}>{index===questions.length-1?"查看結果":"下一題"}</PrimaryButton></div></BottomActionBar></section>;
}

export function AnalyzingStep({error,back}:{error:string;back():void}) { return <section className="dna-step analyzing"><div className="orbit"><i/><i/><i/></div><h1>{error?"分析遇到了一點問題":"正在解析你們的婚禮個性"}</h1><div className="analysis-copy" aria-live="polite"><p>正在比對適合的空間氛圍</p><p>正在整理專屬推薦</p></div>{error?<><p>{error}</p><PrimaryButton onClick={back}>返回測驗</PrimaryButton></>:null}</section>; }

export function PersonalityResultStep({session,next,back}:{session:RecommendationSession;next():void;back():void}) { const r=session.quizResult!; const p=getPersonalityById(r.primaryPersonality!.id)!; const s=getPersonalityById(r.secondaryPersonality!.id)!; const card=p.resultCard!; const top=[...WEDDING_PERSONALITY_WEIGHT_KEYS].sort((a,b)=>r.dimensionScores[b]-r.dimensionScores[a]).slice(0,3); return <section className="dna-step personality-step"><p className="eyebrow">YOUR WEDDING DNA</p><article className="personality-result"><span>{r.primaryPersonality!.score}% 匹配</span><h1>{p.displayName}</h1><h2>{p.subtitle}</h2><blockquote>{card.headline}</blockquote><p>{card.summary}</p><p>{p.description}</p><div className="chips">{p.keywords.map(x=><i key={x}>{x}</i>)}</div></article><p className="secondary">你也帶有一些<strong>{s.displayName}</strong>的特質</p><div className="top-dimensions"><h3>你們最重視的三件事</h3>{top.map((x,i)=><div key={x}><b>0{i+1}</b><span>{labels[x]}</span></div>)}</div><PersonalityStoryContent personality={p}/><BottomActionBar secondaryAction={{label:"返回",onClick:back}} primaryAction={{label:"查看推薦廳房",onClick:next}}/></section>; }

export function HallResultsStep({session,toggleCompare,detail,next,back,goCompare}:{session:RecommendationSession;toggleCompare(id:string):void;detail(id:string):void;next():void;back():void;goCompare():void}) { const primary=session.recommendations.filter(r=>r.recommendationTier==="primary").slice(0,3); const comfort=session.recommendations.filter(r=>r.recommendationTier==="comfort").slice(0,3); const official=[...primary,...comfort]; const selected=session.comparisonHallIds.length; return <section className={`dna-step hall-results ${selected?"has-contextual-action":""}`}><p className="eyebrow">HALL RECOMMENDATIONS</p><h1>{official.length?"最適合你們的廳房":"風格高匹配候選"}</h1>{!official.length?<p className="notice">目前沒有可確認容量的正式推薦；以下候選需由婚禮顧問確認容量。</p>:null}{primary.length?<><h2>最佳推薦</h2><div className="hall-list">{primary.map((r,i)=><HallRecommendationCard key={r.hallId} result={r} rank={i+1} compared={session.comparisonHallIds.includes(r.hallId)} onCompare={()=>toggleCompare(r.hallId)} onDetail={()=>detail(r.hallId)}/>)}</div></>:null}{comfort.length?<><h2>舒適推薦</h2><div className="hall-list">{comfort.map((r,i)=><HallRecommendationCard key={r.hallId} result={r} rank={i+1} compared={session.comparisonHallIds.includes(r.hallId)} onCompare={()=>toggleCompare(r.hallId)} onDetail={()=>detail(r.hallId)}/>)}</div></>:null}{session.manualConfirmationHalls.length?<><h2>容量需人工確認</h2><div className="hall-list manual-list">{session.manualConfirmationHalls.slice(0,4).map(r=><HallRecommendationCard key={r.hallId} result={r} compared={session.comparisonHallIds.includes(r.hallId)} onCompare={()=>toggleCompare(r.hallId)} onDetail={()=>detail(r.hallId)}/>)}</div></>:null}<BottomActionBar secondaryAction={{label:"返回",onClick:back}} primaryAction={{label:"繼續查看",onClick:next}} contextualAction={selected?{description:`已選擇 ${selected} 個廳房`,label:selected>=2?"前往比較":"再選 1 個即可比較",disabled:selected<2,onClick:goCompare}:undefined}/></section>; }

const boolText=(v:boolean|null)=>v===null?"待確認":v?"有":"未提供";
export function HallComparisonStep({session,remove,next,back}:{session:RecommendationSession;remove(id:string):void;next():void;back():void}) { return <section className="dna-step comparison"><p className="eyebrow">COMPARE HALLS</p><h1>廳房比較</h1><p>左右滑動查看，最多保留 3 個。</p><div className="comparison-scroll">{session.comparisonHallIds.map(id=>{const h=hallById(id)!;const r=[...session.recommendations,...session.manualConfirmationHalls].find(x=>x.hallId===id)!;const text=[...h.features,...h.salesNotes.internalNotes].join(" ");const height=text.match(/(\d+(?:\.\d+)?)\s*米/)?.[1]??"待確認";const area=text.match(/(\d+(?:\.\d+)?)\s*坪/)?.[1]??"待確認";return <article key={id}><button onClick={()=>remove(id)}>移除 ×</button><h2>{h.displayName}</h2><p>{h.floor??"樓層待確認"}</p><dl><dt>最大桌數</dt><dd>{h.capacity.maximumTables??"待確認"}</dd><dt>舒適桌數</dt><dd>{comfortText(h)}</dd><dt>挑高</dt><dd>{height}{height!=="待確認"?" 米":""}</dd><dt>坪數</dt><dd>{area}{area!=="待確認"?" 坪":""}</dd><dt>LED</dt><dd>{boolText(h.equipment.ledScreen)}{h.equipment.ledScreenSizeInches?` ${h.equipment.ledScreenSizeInches}吋`:""}</dd><dt>電視</dt><dd>{boolText(h.equipment.tv)}{h.equipment.tvSizeInches?` ${h.equipment.tvSizeInches}吋`:""}</dd><dt>星光走道</dt><dd>{boolText(h.equipment.starLightAisle)}</dd><dt>空中纜車</dt><dd>{boolText(h.equipment.aerialCableEntrance)}</dd><dt>鉛錘</dt><dd>{h.equipment.hangingGiftDeviceCount||"未提供"}</dd><dt>自然採光</dt><dd>{text.includes("自然採光")?"有":"待確認"}</dd><dt>婚禮風格</dt><dd>{h.style.designStyles.slice(0,3).join("、")||"待確認"}</dd><dt>匹配分數</dt><dd>{r.normalizedScore}%</dd><dt>容量狀態</dt><dd>{r.capacityStatus==="eligible"?"符合":"人工確認"}</dd></dl></article>})}</div><BottomActions><button onClick={back}>返回推薦</button><PrimaryButton onClick={next}>繼續</PrimaryButton></BottomActions></section>; }

export function CeremonyAddonStep({session,setSession,next,back}:{session:RecommendationSession;setSession:Setter;next():void;back():void}) {const c=hallsData.ceremonySpaces.find(x=>x.status==="active"&&x.requiresBanquetBooking)!;return <section className="dna-step"><p className="eyebrow">CEREMONY · THE NEXT CHAPTER</p><h1>讓誓言，成為婚宴前最正式的一頁</h1><p>{c.displayName}</p><p className="notice">{c.bookingRule.summary}，不可單獨預訂。</p><div className="ceremony-options">{c.spaceOptions.map(x=><article key={x.id}><h2>{x.displayName}</h2><p>{x.style.designStyles.join("、")}</p></article>)}</div><h3>使用時段</h3><ul>{c.availableTimeSlots.map(x=><li key={x.banquetTimeSlot}>{x.banquetTimeSlot==="lunch"?"午宴":"晚宴"}：{x.startTime}–{x.endTime}</li>)}</ul><p>場地使用時間：{c.durationMinutes} 分鐘</p><h3>專案包含</h3><div className="chips">{c.packageIncludes.map(x=><i key={x}>{x}</i>)}</div><h3>可加購</h3><p>{c.optionalAddOns.join("、")}</p><div className="interest-buttons" role="radiogroup" aria-label="證婚儀式興趣"><button role="radio" aria-checked={session.ceremonyInterest===true} className={session.ceremonyInterest===true?"selected":""} onClick={()=>setSession(s=>({...s,ceremonyInterest:true}))}>我有興趣了解</button><button role="radio" aria-checked={session.ceremonyInterest===false} className={session.ceremonyInterest===false?"selected":""} onClick={()=>setSession(s=>({...s,ceremonyInterest:false}))}>暫時不需要</button></div><BottomActions><button onClick={back}>返回</button><PrimaryButton disabled={session.ceremonyInterest===null} onClick={next}>下一步</PrimaryButton></BottomActions></section>}

export function ContactStep({session,setSession,submit,back,errors,submitting}:{session:RecommendationSession;setSession:Setter;submit():void;back():void;errors:string[];submitting:boolean}) {
 const c=session.contactInfo; const candidates=[...session.recommendations,...session.manualConfirmationHalls].filter((x,i,a)=>a.findIndex(y=>y.hallId===x.hallId)===i).slice(0,6);
 const update=(key:string,value:unknown)=>setSession(s=>({...s,contactInfo:{...s.contactInfo,[key]:value}}));
 const toggleHall=(id:string)=>update("preferredHallIds",c.preferredHallIds.includes(id)?c.preferredHallIds.filter(x=>x!==id):[...c.preferredHallIds,id]);
 return <section className="dna-step"><p className="eyebrow">KEEP IN TOUCH</p><h1>留下聯絡方式</h1><p>這些資料會交給接待你們的婚禮顧問，<br/>日期還沒決定也完全沒關係。</p>{session.migrationWarnings.map(x=><p className="migration-warning" role="alert" key={x}>{x}</p>)}<div className="form-grid section-card"><label htmlFor="groom-name">新郎姓名 *<input id="groom-name" placeholder="請輸入新郎姓名" value={c.groomName} autoComplete="name" onChange={e=>update("groomName",e.target.value)}/></label><label htmlFor="bride-name">新娘姓名 *<input id="bride-name" placeholder="請輸入新娘姓名" value={c.brideName} autoComplete="name" onChange={e=>update("brideName",e.target.value)}/></label><label>聯絡電話 *<input type="tel" inputMode="tel" value={c.phone} autoComplete="tel" onChange={e=>update("phone",e.target.value)}/></label><label>Email<input type="email" value={c.email} autoComplete="email" onChange={e=>update("email",e.target.value)}/></label>{candidates.length?<fieldset className="hall-interest full"><legend>有興趣的廳房</legend>{candidates.map(x=><label key={x.hallId}><input type="checkbox" checked={c.preferredHallIds.includes(x.hallId)} onChange={()=>toggleHall(x.hallId)}/>{x.displayName}</label>)}</fieldset>:null}<label className="full">備註<textarea value={c.notes} onChange={e=>update("notes",e.target.value)}/></label><label className="check full"><input type="checkbox" checked={c.privacyConsent} onChange={e=>update("privacyConsent",e.target.checked)}/> 我同意典華為婚宴諮詢與聯絡目的使用上述資料 *</label></div>{errors.length?<div className="inline-errors">{errors.map(x=><p key={x}>{x}</p>)}</div>:null}<BottomActions><button onClick={back}>返回</button><PrimaryButton disabled={submitting} onClick={submit}>{submitting?"送出中…":"送出給婚禮顧問"}</PrimaryButton></BottomActions></section>
}

export function CompletedStep({session,results,restart}:{session:RecommendationSession;results():void;restart():void}) {const primary=getPersonalityById(session.quizResult!.primaryPersonality!.id)!;const first=session.recommendations[0];return <section className="dna-step completed"><span className="success-mark">✓</span><p className="eyebrow">SUBMITTED</p><h1>{session.contactInfo.groomName} &amp; {session.contactInfo.brideName}<br/>謝謝你們</h1><p>婚禮的輪廓已經出現了</p><dl><dt>主要人格</dt><dd>{primary.displayName}</dd><dt>第一推薦</dt><dd>{first?.displayName??"容量需由顧問確認"}</dd><dt>比較廳房</dt><dd>{session.comparisonHallIds.map(id=>hallById(id)?.displayName).filter(Boolean).join("、")||"尚未選擇"}</dd><dt>證婚儀式</dt><dd>{session.ceremonyInterest?"有興趣了解":"暫時不需要"}</dd></dl><p>資料已保存在此裝置的送出紀錄中，婚禮顧問將依你留下的方式與你聯繫。</p><div className="completed-buttons"><PrimaryButton onClick={results}>重新查看結果</PrimaryButton><button onClick={restart}>重新開始</button></div></section>}
