"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { calculateQuizResult } from "../../lib/quizScoring";
import { rankHallsForBasicInfo } from "../../lib/recommendationEngine";
import { addComparisonHall, createRecommendationSession, removeComparisonHall, restoreRecommendationSession, SESSION_STORAGE_KEY, validateBasicInfo, validateContactInfo } from "../../lib/sessionState";
import { mockSubmit } from "../../lib/submission";
import type { RecommendationSession, RecommendationStep } from "../../types/recommendation-session";
import { HallDetailModal } from "./HallComponents";
import { ErrorState, ProgressIndicator } from "./Ui";
import { WelcomeStep,BasicInfoStep,QuizStep,AnalyzingStep,PersonalityResultStep,HallResultsStep,HallComparisonStep,CeremonyAddonStep,ContactStep,CompletedStep } from "./Steps";

const order: RecommendationStep[]=["welcome","basic-info","quiz","analyzing","personality-result","hall-results","hall-comparison","ceremony-addon","contact","completed"];
const labels:Record<RecommendationStep,string>={welcome:"開始", "basic-info":"基本資料",quiz:"婚禮測驗",analyzing:"分析中","personality-result":"人格結果","hall-results":"廳房推薦","hall-comparison":"廳房比較","ceremony-addon":"證婚加購",contact:"聯絡資料",completed:"完成"};
const previous:Partial<Record<RecommendationStep,RecommendationStep>>={"basic-info":"welcome",quiz:"basic-info","personality-result":"quiz","hall-results":"personality-result","hall-comparison":"hall-results","ceremony-addon":"hall-results",contact:"ceremony-addon",completed:"contact"};

export default function WeddingDnaApp(){
 const [session,setSession]=useState<RecommendationSession>(()=>createRecommendationSession()); const [ready,setReady]=useState(false);const [storageWarning,setStorageWarning]=useState("");const [basicErrors,setBasicErrors]=useState<string[]>([]);const [contactErrors,setContactErrors]=useState<string[]>([]);const [quizIndex,setQuizIndex]=useState(0);const [analysisError,setAnalysisError]=useState("");const [detailId,setDetailId]=useState<string|null>(null);const [submitting,setSubmitting]=useState(false);const submitLock=useRef(false);
 const go=useCallback((step:RecommendationStep)=>{setSession(s=>({...s,currentStep:step}));try{history.replaceState({step},"",location.href)}catch{}},[]);
 useEffect(()=>{const timer=setTimeout(()=>{try{const saved=restoreRecommendationSession(localStorage.getItem(SESSION_STORAGE_KEY));if(saved)setSession(saved)}catch{setStorageWarning("此瀏覽器目前無法保存進度，請避免重新整理頁面。")}setReady(true)},0);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(SESSION_STORAGE_KEY,JSON.stringify({...session,updatedAt:new Date().toISOString()}))}catch{setTimeout(()=>setStorageWarning("此瀏覽器目前無法保存進度，請避免重新整理頁面。"),0)}},[session,ready]);
 useEffect(()=>{if(session.currentStep!=="analyzing"||analysisError)return;const timer=setTimeout(()=>go("personality-result"),2600);return()=>clearTimeout(timer)},[session.currentStep,analysisError,go]);
 useEffect(()=>{const handler=()=>{const state=restoreRecommendationSession(localStorage.getItem(SESSION_STORAGE_KEY));if(state)setSession(state)};window.addEventListener("popstate",handler);return()=>window.removeEventListener("popstate",handler)},[]);
 const back=()=>{const target=previous[session.currentStep];if(target)go(target)};
 const beginQuiz=()=>{const errors=validateBasicInfo(session.basicInfo);setBasicErrors(errors);if(!errors.length)go("quiz")};
 const analyze=()=>{try{const quizResult=calculateQuizResult(session.answers);if(!quizResult.isComplete)throw new Error("請完成全部 5 題後再查看結果。");const ranked=rankHallsForBasicInfo(session.basicInfo,quizResult);setSession(s=>({...s,currentStep:"analyzing",quizResult,recommendations:ranked.recommendations}));setAnalysisError("")}catch{setAnalysisError("目前無法完成分析，請返回測驗確認每一題都已作答。");go("analyzing")}}
 const toggleCompare=(id:string)=>{try{setSession(s=>({...s,comparisonHallIds:s.comparisonHallIds.includes(id)?removeComparisonHall(s.comparisonHallIds,id):addComparisonHall(s.comparisonHallIds,id)}))}catch(error){alert(error instanceof Error?error.message:"最多只能比較 3 個廳房。")}};
 const openDetail=(id:string)=>setDetailId(id);const selectedDetail=useMemo(()=>session.recommendations.find(x=>x.hallId===detailId)??null,[detailId,session]);
 const toContact=()=>{const preferred=session.comparisonHallIds.length?session.comparisonHallIds:session.recommendations[0]?[session.recommendations[0].hallId]:[];setSession(s=>({...s,currentStep:"contact",contactInfo:{...s.contactInfo,preferredHallIds:preferred}}))};
 const submit=async()=>{if(submitLock.current||session.submissionId)return;const errors=validateContactInfo(session.contactInfo);setContactErrors(errors);if(errors.length)return;submitLock.current=true;setSubmitting(true);try{const result=await mockSubmit(session,localStorage);setSession(s=>({...s,submissionId:result.submissionId,currentStep:"completed"}))}catch{setContactErrors(["資料暫時無法送出，請稍後再試；已填內容仍然保留。"])}finally{submitLock.current=false;setSubmitting(false)}};
 const restart=()=>{if(!confirm("確定要重新開始嗎？目前填寫內容會被清除。"))return;if(!confirm("再次確認：要清除這次 Wedding DNA 進度嗎？"))return;const fresh=createRecommendationSession();try{localStorage.removeItem(SESSION_STORAGE_KEY)}catch{}setSession(fresh);setQuizIndex(0)};
 if(!ready)return <main className="dna-shell"><section className="dna-step analyzing"><p>正在恢復進度…</p></section></main>;
 let content;switch(session.currentStep){case"welcome":content=<WelcomeStep next={()=>go("basic-info")}/>;break;case"basic-info":content=<BasicInfoStep session={session} setSession={setSession} next={beginQuiz} back={back} errors={basicErrors}/>;break;case"quiz":content=<QuizStep session={session} setSession={setSession} index={quizIndex} setIndex={setQuizIndex} next={analyze} back={back}/>;break;case"analyzing":content=<AnalyzingStep error={analysisError} back={()=>go("quiz")}/>;break;case"personality-result":content=session.quizResult?<PersonalityResultStep session={session} next={()=>go("hall-results")} back={()=>go("quiz")}/>:<ErrorState message="找不到測驗結果，請返回重新確認答案。"/>;break;case"hall-results":content=<HallResultsStep session={session} toggleCompare={toggleCompare} detail={openDetail} next={()=>go("ceremony-addon")} back={back} goCompare={()=>session.comparisonHallIds.length>=2&&go("hall-comparison")}/>;break;case"hall-comparison":content=session.comparisonHallIds.length>=2?<HallComparisonStep session={session} remove={toggleCompare} next={()=>go("ceremony-addon")} back={back}/>:<ErrorState message="請先選擇至少 2 個廳房再進行比較。" action={<button onClick={()=>go("hall-results")}>返回推薦結果</button>}/>;break;case"ceremony-addon":content=<CeremonyAddonStep session={session} setSession={setSession} next={toContact} back={back}/>;break;case"contact":content=<ContactStep session={session} setSession={setSession} submit={submit} back={back} errors={contactErrors} submitting={submitting}/>;break;default:content=<CompletedStep session={session} results={()=>go("hall-results")} restart={restart}/>}
 return <main className="dna-shell"><header><Link href="/">DENWELL · WEDDING DNA</Link><button onClick={restart}>重新開始</button></header>{session.currentStep!=="welcome"&&session.currentStep!=="completed"?<ProgressIndicator step={order.indexOf(session.currentStep)} label={labels[session.currentStep]}/>:null}{storageWarning?<div className="storage-warning">{storageWarning}</div>:null}{content}<HallDetailModal result={selectedDetail} onClose={()=>setDetailId(null)}/></main>;
}
